### ISSUE TITLE
package v2

### ISSUE THREAD

**Issue by newbenji** [exoscale/egoscale#574]
Any plans to release v2 ?

**Comment by 7fELF** [comment]
Hello @newbenji
You can already use egoscale v2.

Example in our CLI: 
- https://github.com/exoscale/cli/blob/master/cmd/client.go#L10
- https://github.com/exoscale/cli/blob/master/go.mod#L14
Doc: https://pkg.go.dev/github.com/exoscale/egoscale@v0.97.0/v2

There is a bug with the Go docsite that we need to find a workaround for, it always points to  `v1.19.0` by default. It was pushed by mistake instead of ` v0.19.0` a while ago.

Don't hesitate if you have additional questions :wink:

**Comment by newbenji** [comment]
just close it.. works with 0.97.0
